#!/bin/bash
####################################
# @Author: juliolimareis@gmail.com #
# Script exibir mensagens na       # 
# interface e console              #  
####################################

# * Documentação das funções *
# con: console
# ui: interface

# msg_ui "mensagem" "nameIcon" => (Arquivos .png em ./icons)

# msg_con_success "mensagem"
# msg_con_alert "mensagem"
# msg_con_error "mensagem" "mensagemErro"

# msg_con_color_0 "mensagem" "codigoCor"
# msg_con_color_1 "mensagem" "codigoCor"
# msg_con_person  "mensagem" "codigoCor" "typeColor"

# msg_con_background "mensagem" "codigoCor" "typeBackgroud"

# printColors mostra as cores e seus códigos

# * Codigo cores (TypeColor = 0) *

# corPadrao="0"
# preto="30"
# vermelho="31"
# verde="32"
# marrom="33"
# azul="34"
# purple="35"
# cyan="36"
# cinzaClaro="37"

# * Cores Claras (TypeColor = 1) *

# pretoCinza="1;30"
# vermelhoClaro="1;31"
# verdeClaro="1;32"
# amarelo="1;33"
# azulClaro="1;34"
# purpleClaro="1;35"
# cyanClaro="1;36"
# branco="1;37"

pathIcon="$HOME/healthmap/script/msg/icons"

function msg_ui(){
    notify-send "$1" --icon="$pathIcon/$2.png"
}
############# combo messages console and notification ################
function messagesSuccess(){
	consoleSuccess "$1"
	NotificationSuccess "$1"
}

function messagesWarning(){
	consoleWarning "$1"
	NotificationWarning "$1"
}

function messagesError(){
	consoleError "$1" "$2"
	NotificationError "$1: ($2)"
}

############# messages console ################
function consoleSuccess(){
    echo -e "\033[1;32m$1\033[0m"
}

function consoleWarning(){
	echo -e "\033[1;33m$1\033[0m"
}

function consoleError(){
    echo -e "\033[1;31mError($2): $1 \033[0m"
}
############# messages sistem notification ################
function NotificationSuccess(){
	msg_ui "$1" "correct"
}

function NotificationWarning(){
	msg_ui "$1" "alert"
}

function NotificationError(){
	msg_ui "$1" "error"
}

############## Old console messages #################

function msg_con_success(){
    echo -e "\033[1;32m$1\033[0m"
}

function msg_con_alert(){
    echo -e "\033[1;33m$1\033[0m"
}

function msg_con_error(){
    echo -e "\033[1;31mError($2): $1 \033[0m"
}

function msg_con_color_0(){
    echo -e "\033[0;$2m$1\033[0m"
}

function msg_con_color_1(){
    echo -e "\033[0;$2m$1\033[0m"
}

function msg_con_person(){
    echo -e "\033[$3;$2m$1\033[0m"
}

function msg_con_background(){
    echo -e "\033[$3;1;$2m$1\033[0m"
}

function printColors(){
    echo "Imprimindo cores"
    echo -e " \033[0;30m Preto  \033[0m             --> 0;30 "
    echo -e " \033[0;31m Vermelho  \033[0m          --> 0;31 "
    echo -e " \033[0;32m Verde  \033[0m             --> 0;32 "
    echo -e " \033[0;33m Marrom  \033[0m            --> 0;33 "
    echo -e " \033[0;34m Azul  \033[0m              --> 0;34 "
    echo -e " \033[0;35m Purple  \033[0m            --> 0;35 "
    echo -e " \033[0;36m Cyan  \033[0m              --> 0;36 "
    echo -e " \033[0;37m Cinza Claro  \033[0m       --> 0;37 "
    echo -e " \033[1;30m Preto Acinzentado \033[0m  --> 1;30 "
    echo -e " \033[1;31m Vermelho Claro  \033[0m    --> 1;31 "
    echo -e " \033[1;32m Verde Claro  \033[0m       --> 1;32 "
    echo -e " \033[1;33m Amarelo \033[0m            --> 1;33 "
    echo -e " \033[1;34m Azul  Claro \033[0m        --> 1;34 "
    echo -e " \033[1;35m Purple Claro  \033[0m      --> 1;35 "
    echo -e " \033[1;36m Cyan  Claro \033[0m        --> 1;36 "
    echo -e " \033[1;37m Branco  \033[0m            --> 1;37 "

    echo -e " \033[40;1;37m Fundo Preto    \033[0m     --> 40;?;? "
    echo -e " \033[41;1;37m Fundo Vermelho \033[0m     --> 41;?;? "
    echo -e " \033[42;1;37m Fundo Verde    \033[0m     --> 42;?;? "
    echo -e " \033[43;1;37m Fundo Marrom   \033[0m     --> 43;?;? "
    echo -e " \033[44;1;37m Fundo Azul     \033[0m     --> 44;?;? "
    echo -e " \033[45;1;37m Fundo Purple   \033[0m     --> 45;?;? "
    echo -e " \033[46;1;37m Fundo Cyan     \033[0m     --> 46;?;? "
    echo -e " \033[47;1;37m Fundo Cinza    \033[0m     --> 47;?;? "

    echo -e " \033[4;30m Sublinhado  \033[0m        --> 4;? "
    echo -e " \033[5;30m Piscando    \033[0m        --> 5;? "
    echo -e " \033[7;30m Invertido   \033[0m        --> 7;? "
    echo -e " \033[8;30m Concealed   \033[0m        --> 8;? "
}