#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script Abrir dados dos clientes         #
# @depedency: sudo apt install xsel
#########################################################

# para fazer clipboard.
# instalar xsel
# cat $dirClients/$1 | xsel -ib 

dirClients="$HOME/healthmap/documentos/.clients"
dirProperties="$HOME/healthmap/healthmap_web/healthmap/WEB-INF/healthmap.properties"

function resetProperties(){
  hm 2>&1&> /dev/null
  git checkout $dirProperties
  echo -e "\033[1;33m ==== healthmap.properties resetado ==== \033[0m"
}

function removeServerConnection(){
  sed -i '/^myServerName/d' $dirProperties
  sed -i '/^myInstanceName/d' $dirProperties
  sed -i '/^myDatabase/d' $dirProperties
  sed -i '/^myUser/d' $dirProperties
  sed -i '/^mySenha/d' $dirProperties
}

function refreshProperties(){
	#verifica erros
	client=$(cat $dirClients/$1) #2>&1&> /dev/null

	if [ $? != 0 ]; then
    clear
    echo -e "\033[1;31mError(directory not exit): cliente \033[1;32m$1\033[0m \033[1;31mnão cadastrado. \033[0m"
    echo -e "\033[1;33m ==== Programa finalizado ==== \033[0m"
    exit
	fi

	#Reseta o arquivo healthma.properties
	resetProperties
	#remove as linhas que faz a conexão com o banco
	removeServerConnection
	# Adiciona a conexao do cliente selecionado na linha 3
	sed -i "3i $client\n" $dirProperties
	echo -e "\033[1;33mCliente adicionado no properties\033[0m"
}

function addClient(){
	echo "nome do cliente: "
	read name
	echo "myServerName: "
	read myServerName
	echo "myDatabase: "
	read myDatabase
	echo "myUser: "
	read myUser
	echo "mySenha: "
	read mySenha

	echo "#$name\nmyServerName=$myServerName\nmyInstanceName=\nmyDatabase=$myDatabase\nmyUser=$myUser\nmySenha=$mySenha" > $dirClients/$name
	echo -e "\033[1;32m * Clientes cadastrado.\033[0m"
}

function listClients(){
  ls $dirClients
}

function listClient(){
  if [ -n $1 ]; then
    cat "$dirClients/$1"
  else
    listClients
  fi
}

case "$1" in
  "-r"|"reset")
    resetProperties
  ;;
  "-a"|"add")
    addClient
  ;;
  "-l"|"list")
    if [ -n $2 ]; then
      listClient $2
    else
      listClients
    fi
  ;;
  ""|"-h"|"help")
    echo -e "\033[1;32m * Clientes cadastrados * \033[0m"
    echo -e "\033[1;37m`ls $dirClients`\033[0m"
    echo ""
    echo "Pegar dados do cliente: comando <nome_cliente>"
    echo "Adicionar ou atualizar cliente: comando add ou -a"
  ;;
  *)
    refreshProperties $1
  ;;
esac

exit





