#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script Abrir dados dos clientes         #
# @depedency: sudo apt install xsel
#########################################################

directory="$HOME/healthmap/documentos/.clients"

# verifica se prametro $1 esta vazio
if [ -z $1 ]; then
    echo -e "\033[1;32m * Clientes cadastrados * \033[0m"
    echo -e "\033[1;37m`ls $directory`\033[0m"
    echo ""
    echo "Pegar dados do cliente: client <nome_cliente>"
    exit
fi

#verifica erros
cat $directory/$1 2>&1&> /dev/null

if [ $? != 0 ]; then
    clear
    echo -e "\033[1;31mError(directory not exit): cliente \033[1;32m$1\033[0m \033[1;31mnão cadastrado. \033[0m"
    echo -e "\033[1;33m ==== Programa finalizado ==== \033[0m"
    exit
fi

#fazendo clipboard.
cat $directory/$1 | xsel -ib 
cat $directory/$1
echo -e "\033[1;33mCliente copiado para seleção\033[0m"

exit





