#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script Abrir healthmap em homologação   #
# @Exemples: prod app02                                 #
# Parametros: prod app02 -m                             #
#   -m (mnu.jsp): Abrir página do .properties           #
#   -l (link): mostrar link da aplicação                #
#########################################################

browse="chromium"

declare -A client=(
    # ['app01']='https://app01-homolog.healthmap.com.br'
    #['app02']='https://app02-homolog.healthmap.com.br'
    ['app02']='https://app02.hmg.healthmap.com.br'
    #['app03']='https://app03-homolog.healthmap.com.br'
    ['app03']='https://app03.hmg.healthmap.com.br'
    ['unimedse']='https://unimedse-homolog.healthmap.com.br'
    ['unimedgoiania']="https://unimedgoiania-homolog.healthmap.com.br"
    ['unimedvitoria']='https://unimedvitoria-homolog.healthmap.com.br'
    ['poa']='https://unimedpa.hmg.healthmap.com.br'
)

if [ -z $1 ]; then
    echo -e "\033[1;32m * Comando hmg * \033[0m"
    for i in "${!client[@]}"; do
        echo -e "\033[1;35m$i \033[1;31m=> \033[1;36m${client[$i]}\033[0m"
    done
    echo ""
    echo "Acessar link: hmg <nome_base>"
    echo "Verificar se link esta cadastrado: hmg <nome_base> -l"
    echo "Acessar dados da base (mnu.jsp): hmg <nome_base> -m"
    exit
fi

if [ -z ${client[$1]} ]; then
    echo -e "\033[1;31mError(option 404): Opção não encontrada. \033[0m"
fi

if [ "$2" == "-l" ]; then
    echo -e "\033[1;36m${client[$1]}\033[0m"
elif [ "$2" == "-m" ]; then
    $browse ${client[$1]}/ini_manipulation.jsp?acao=login
else
    $browse ${client[$1]}
fi

exit
