#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Lista de programas para instalar        # 
#########################################################

sudo apt install xfce4-screenshooter
