#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script                        # 
#########################################################
echo teste
echo 's/^\s*./\U&\E/g' $@ 