#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script para abrir vscode em root mode   # 
# Depende: Script msg
#########################################################
source "$HOME/healthmap/script/msg/msg"

dirConf="$HOME/.config/Code"
dirScripts="$HOME/julio/healthmap/script"
icon="$HOME/Imagens/icons/code.purple.png"
exec="$HOME/healthmap/script/vscode-purple"
userPasswd=$(cat $HOME/.pfkdgj494fdfdg)

function configDesktopShortcut(){
	echo -e "
[Desktop Entry]
Name=Visual Studio Code Purple
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=$exec
Icon=$icon
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.24" > "$HOME/.local/share/applications/code.desktop"

# [Desktop Action Nova Janela Vazia]
# Name=New Empty Window
# Exec=$exec
# Icon=$icon

if [ $? != 0 ]; then
	echo -e "\033[0;31mError(file getate): Operação cancelada. \033[0m"
	exit
fi

echo -e "\033[1;32m * Desktop Atalho gerado => $HOME/.local/share/applications* \033[0m"
exit
}

function help(){
	echo -e "\033[1;33m ===== Conado vscode purple ===== \033[0m"
	echo -e "\033[1;33m Executa vscode em modulo root \033[0m"
	echo "" # configurar
	echo -e "\033[1;37m Criar atalho para executar vscode-purple: \033[0m"
	echo -e "\033[1;32m $ vscode-purple config \033[0m"
	echo "" # modulo
	echo -e "\033[1;37m Executa vscode em modulo root: \033[0m"
	echo -e "\033[1;32m $ vscode-purple  \033[0m"
	echo ""
	verifyUserPasswdConfig
	echo -e "\033[1;37mBy <juliolimareis@gmail.com>\033[0m"
	exit
}

function verifyUserPasswdConfig(){
	if [ -z $userPasswd ]; then 
		messagesError "Passwd not configured" "userPasswd not found"
		messagesWarning "Você pode configurar a senha com o comando install-commands -p"
		exit
	fi
}

function execVscode(){
	verifyUserPasswdConfig
	consoleSuccess "vscode in root mode"
	echo -e $userPasswd | sudo -S code --user-data-dir $dirConf
	if [ $? != 0 ]; then
	  messagesError "Erro ao tentar executar vscode" "Unexpected"
		exit
	fi
}

case "$1" in
  "config"|"c"|"-c") #configura o atalho
		configDesktopShortcut
  ;;
  "h"|"-h"|"help"|"-help"|"--help") #help
		help
  ;;
  "") #sem parâmetro executar vscode
		# exec="code --user-data-dir ~/.config/Code --no-sandbox --new-window %F"
		execVscode
  ;;
  *)
		echo -e "\033[0;31mError(Not found: $1): Operação não encontrada. \033[0m"
  ;;
esac
exit